name:        lht
version:     0.0.0.1
synopsis:    AWS Lambda haskell tool
homepage:    https://github.com/mbj/lht
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2019 Markus Schirp
github:      mbj/lht
license:     BSD3

extra-source-files:
- aws/rds-ca-2019-root.pem

dependencies:
- amazonka           == 1.6.1
- amazonka-core      == 1.6.1
- amazonka-s3        == 1.6.1
- base               ^>= 4.13
- bytestring         ^>= 0.10
- cbt                ^>= 0.1.0
- conversions        ^>= 0.0.3
- directory          ^>= 1.3
- exceptions         ^>= 0.10
- http-types         ^>= 0.12
- mprelude           ^>= 0.2
- pathtype           ^>= 0.8
- source-constraints ^>= 0.0.1
- tar                ^>= 0.5
- template-haskell   ^>= 2.15
- text               ^>= 1.2
- text-conversions   ^>= 0.3
- th-lift-instances  ^>= 0.1
- time               ^>= 1.9
- typed-process      ^>= 0.2
- unix               ^>= 2.7
- unliftio           ^>= 0.2
- unliftio-core      ^>= 0.1
- uuid               ^>= 1.3
- zip-archive        ^>= 0.4

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

default-extensions:
- CPP
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- Strict
- TemplateHaskell

library:
  source-dirs:
  - src
  exposed-modules:
  - LHT.Build
  - LHT.Deploy
  - LHT.Executable
  - LHT.S3
  - LHT.Zip

tests:
  devtools:
    main: test/Test.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
    - elf           ^>= 0.30
    - lht
    - tasty         ^>= 1.3
    - tasty-hunit   ^>= 0.10
