name:        lambda-haskell-runtime
version:     0.0.0.1
synopsis:    An alpine based statically compiled haskell runtime
homepage:    https://github.com/mbj/lambda-haskell-runtime
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2019 Markus Schirp
github:      mbj/lambda-haskell-runtime

dependencies:
- amazonka           == 1.6.1
- amazonka-core      == 1.6.1
- amazonka-s3        == 1.6.1
- base               == 4.12.0.0
- bytestring         == 0.10.8.2
- directory          == 1.3.3.0
- exceptions         == 0.10.2
- filepath           == 1.4.2.1
- http-types         == 0.12.3
- mprelude           == 0.0.0.1
- source-constraints == 0.0.0.1
- tar                == 0.5.1.0
- template-haskell   == 2.14.0.0
- text               == 1.2.3.1
- text-conversions   == 0.3.0
- th-lift-instances  == 0.1.12
- time               == 1.8.0.2
- typed-process      == 0.2.5.0
- unix               == 2.7.2.2
- unliftio           == 0.2.11
- unliftio-core      == 0.1.2.0
- zip-archive        == 0.4.1

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

default-extensions:
- CPP
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- Strict
- TemplateHaskell

library:
  source-dirs:
  - src
  exposed-modules:
  - AWS.Lambda.Runtime.Deploy
  - AWS.Lambda.Runtime.Podman

tests:
  hlint:
    main:          HLint.hs
    source-dirs:   test
    other-modules: []
    dependencies:
    - hlint == 2.1.11
