name:        lambda-haskell-runtime
version:     0.0.0.1
synopsis:    An alpine based statically compiled haskell runtime
homepage:    https://github.com/mbj/lambda-haskell-runtime
author:      Markus Schirp
maintainer:  mbj@schirp-dso.com
copyright:   2019 Markus Schirp
github:      mbj/lambda-haskell-runtime

dependencies:
- amazonka           == 1.6.1
- amazonka-core      == 1.6.1
- amazonka-s3        == 1.6.1
- base               ^>= 4.12
- bytestring         ^>= 0.10
- directory          ^>= 1.3
- exceptions         ^>= 0.10
- filepath           ^>= 1.4
- http-types         ^>= 0.12
- mprelude           == 0.0.0.1
- pathtype           ^>= 0.8
- source-constraints == 0.0.0.1
- tar                ^>= 0.5
- template-haskell   ^>= 2.14
- text               ^>= 1.2
- text-conversions   ^>= 0.3
- th-lift-instances  ^>= 0.1
- time               ^>= 1.8
- typed-process      ^>= 0.2
- unix               ^>= 2.7
- unliftio           ^>= 0.2
- unliftio-core      ^>= 0.1
- zip-archive        ^>= 0.4

ghc-options:
- -Wall
- -Wcompat
- -Werror
- -Widentities
- -Wimplicit-prelude
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-exported-signatures
- -Wmissing-local-signatures
- -Wmonomorphism-restriction
- -Wredundant-constraints
- -fplugin=SourceConstraints
- -funbox-strict-fields

default-extensions:
- CPP
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- NumericUnderscores
- OverloadedLists
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- Strict
- TemplateHaskell

library:
  source-dirs:
  - src
  exposed-modules:
  - AWS.Lambda.Runtime.Deploy
  - AWS.Lambda.Runtime.Podman
  - AWS.Lambda.Runtime.S3
  - AWS.Lambda.Runtime.Zip

tests:
  devtools:
    main:          test/Devtools.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - devtools
