build:
  haddock: false
resolver: lts-13.28
extra-deps:
- stratosphere-0.38.0
- git: https://github.com/mbj/mprelude
  commit: 792cda1dc3e51253264aa76eb984b932d428c683
- git: https://github.com/schirp-dso/source-constraints
  commit: c64f467f455f0632eeeb1efa81fa9739985136ad
- git: https://github.com/mbj/stack-deploy
  commit: 012c382b2c83c9f734328e04b3e21ae7a6388f1f
- git: https://github.com/mbj/amazonka
  commit: 33aa6b71309793829b534fb29f6532d71c32b106
  subdirs:
  - amazonka-cloudformation
